#SPDX-License-Identifier: MIT-0
---
# tasks file for db_role
- name: Install MySQL server
  ansible.builtin.apt:
    name: 
      - mysql-server
      - python3-pymysql
      - unzip
    state: present
    update_cache: yes

- name: Copy master.cnf
  template:
    src: templates/master.cnf
    dest: /etc/mysql/mysql.conf.d/master.cnf

- name: Set MySQL bind-address
  ansible.builtin.lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    state: present    

- name: restart mysql
  systemd:
    name: mysql
    state: restarted
    enabled: yes

- name: Create MySQL database
  community.mysql.mysql_db:
    name: joomla
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create a new MySQL user
  community.mysql.mysql_user:
    name: joomla
    host: "10.0.0.%"
    password: "StrongPassword123"
    priv: "joomla.*:ALL PRIVILEGES"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create replication user
  community.mysql.mysql_user:
    name: repl_user
    password: "ReplPassword123"
    host: '%'
    priv: '*.*:REPLICATION SLAVE'
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Dump master database
  community.mysql.mysql_db:
    state: dump
    name: all
    target: "/tmp/all_dump.sql"
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Copy database dump from master
  ansible.builtin.fetch:
    src: "/tmp/all_dump.sql"
    dest: "/tmp/{{ inventory_hostname }}/"
    flat: yes    

- name: Create folder /etc/promtail
  ansible.builtin.file:
    path: /etc/promtail
    state: directory

- name: Unzip promtail
  shell: |
    unzip /vagrant/distr/promtail-linux-amd64.zip -d /tmp/
    mv /tmp/promtail-linux-amd64 /usr/bin/promtail

- name: Copy files service
  ansible.builtin.copy:
    src: templates/promtail.service
    dest: /etc/systemd/system/promtail.service

- name: Copy promtail config
  ansible.builtin.template:
    src: templates/promtail.yml
    dest: /etc/promtail/promtail.yml

- name: Enable promtail.service
  ansible.builtin.systemd_service:
    name: promtail.service
    state: started
    enabled: true
