#SPDX-License-Identifier: MIT-0
---
# tasks file for db_role
- name: Install MariaDB server
  ansible.builtin.apt:
    name: 
      - mariadb-server
      - python3-pymysql
    state: present
    update_cache: yes

- name: Create MariaDB database
  community.mysql.mysql_db:
    name: joomla
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create a new MySQL user
  community.mysql.mysql_user:
    name: joomla
    host: "10.0.0.%"
    password: "StrongPassword123"
    priv: "joomla.*:ALL PRIVILEGES"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
