---
# tasks file for node_exp_role
- name: Unzip node_exporter
  shell: |
    tar -xvzf /vagrant/distr/node_exporter-1.10.2.linux-amd64.tar.gz -C /tmp/
    cp /tmp/node_exporter-1.10.2.linux-amd64/node_exporter /usr/bin/

- name: Copy files service
  ansible.builtin.copy:
    src: templates/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Enable a node_exporter.service
  ansible.builtin.systemd_service:
    name: node_exporter.service
    state: started
    enabled: true