server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.0.0.6:3100/loki/api/v1/push
    tenant_id: 1

scrape_configs:
  - job_name: mysql_error_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: mysql_error
          host: repl 
          __path__: /var/log/mysql/error.log 

  - job_name: mysql_slow_query_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: mysql_slow_query
          host: repl
          __path__: /var/log/mysql/mysql-slow.log