global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 30s
  repeat_interval: 1m
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - chat_id: -1003261555241
        bot_token_file: /opt/telegram.token
        parse_mode: 'HTML'
        message: '{{ template "telegram.message". }}'
        api_url: https://api.telegram.org

templates:
  - '/etc/prometheus/telegram.tmpl'
 