# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - rules.yml
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
       # The label name is added as a label `label_name=<label_value>` to any timeseries scraped from this config.
        labels:
          app: "prometheus"

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 10.0.0.1:9100            
          - 10.0.0.2:9100            
          - 10.0.0.3:9100            
          - 10.0.0.4:9100            
          - 10.0.0.5:9100            
          - 10.0.0.6:9100            

  - job_name: 'nginx_exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 10.0.0.1:9113
        labels:
          app: "nginx"

  - job_name: 'apache_exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 10.0.0.2:9117
          - 10.0.0.3:9117
        labels:
          app: "apache"

  - job_name: 'mysql_exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 10.0.0.4:9104
        labels:
          app: "mysql"
         
