#SPDX-License-Identifier: MIT-0
---
# tasks file for front_role
- name: update
  apt: 
    update_cache=yes

- name: NGINX | Install NGINX
  apt:
    name:
      - nginx
      - iptables-persistent
    state: present
    update_cache: yes

- name: Generate private key
  community.crypto.openssl_privatekey:
    path: "{{ private_key_path }}"
    size: 2048
    mode: '0600'

- name: Generate CSR (Certificate Signing Request)
  community.crypto.openssl_csr:
    path: "{{ csr_path }}"
    privatekey_path: "{{ private_key_path }}"
    common_name: "{{ common_name }}"

- name: Generate self-signed certificate
  community.crypto.x509_certificate:
    path: "{{ cert_path }}"
    privatekey_path: "{{ private_key_path }}"
    csr_path: "{{ csr_path }}"
    provider: selfsigned

- name: NGINX | Create NGINX config file from template
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: set firewall rules
  template:
    src: templates/rules.v4
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: "0644"

- name: Ensure iptables service is enabled and started
  ansible.builtin.service:
    name: iptables
    state: started
    enabled: true
