#SPDX-License-Identifier: MIT-0
---
# tasks file for front_role
- name: update
  apt: 
    update_cache=yes

- name: NGINX | Install NGINX
  apt:
    name:
      - nginx
      - iptables-persistent
      - unzip
    state: present
    update_cache: yes

- name: Generate private key
  community.crypto.openssl_privatekey:
    path: "{{ private_key_path }}"
    size: 2048
    mode: '0600'

- name: Generate CSR (Certificate Signing Request)
  community.crypto.openssl_csr:
    path: "{{ csr_path }}"
    privatekey_path: "{{ private_key_path }}"
    common_name: "{{ common_name }}"

- name: Generate self-signed certificate
  community.crypto.x509_certificate:
    path: "{{ cert_path }}"
    privatekey_path: "{{ private_key_path }}"
    csr_path: "{{ csr_path }}"
    provider: selfsigned

- name: NGINX | Create NGINX config file from template
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: set firewall rules
  template:
    src: templates/rules.v4
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: "0644"

- name: Ensure iptables service is enabled and started
  ansible.builtin.service:
    name: iptables
    state: started
    enabled: true

- name: Create folder /etc/promtail
  ansible.builtin.file:
    path: /etc/promtail
    state: directory

- name: Unzip promtail
  shell: |
    unzip /vagrant/distr/promtail-linux-amd64.zip -d /tmp/
    mv /tmp/promtail-linux-amd64 /usr/bin/promtail
    tar -xvzf /vagrant/distr/nginx-prometheus-exporter_1.5.1_linux_amd64.tar.gz -C /tmp/
    mv /tmp/nginx-prometheus-exporter /usr/bin/

- name: Copy files service
  ansible.builtin.copy:
    src: templates/promtail.service
    dest: /etc/systemd/system/promtail.service

- name: Copy promtail config
  ansible.builtin.template:
    src: templates/promtail.yml
    dest: /etc/promtail/promtail.yml

- name: Enable promtail.service
  ansible.builtin.systemd_service:
    name: promtail.service
    state: started
    enabled: true

- name: Copy files nginx_exporter service
  ansible.builtin.copy:
    src: templates/nginx_exporter.service
    dest: /etc/systemd/system/nginx_exporter.service

- name: Enable nginx_exporter.service
  ansible.builtin.systemd_service:
    name: nginx_exporter.service
    state: started
    enabled: true

