#SPDX-License-Identifier: MIT-0
---
# tasks file for front_role
- name: update
  apt: 
    update_cache=yes

- name: NGINX | Install NGINX
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: NGINX | Create NGINX config file from template
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
